" ~/.dotfiles/host-dev-fedora/config/nvim/Sessions/jupyter.vim:
" Vim session script.
" Created by session.vim 2.13.1 on 14 April 2021 at 19:33:57.
" Open this file in Vim and run :source % to restore your session.

if exists('g:syntax_on') != 1 | syntax on | endif
if exists('g:did_load_filetypes') != 1 | filetype on | endif
if exists('g:did_load_ftplugin') != 1 | filetype plugin on | endif
if exists('g:did_indent_on') != 1 | filetype indent on | endif
if &background != 'dark'
	set background=dark
endif
if !exists('g:colors_name') || g:colors_name != 'ayu' | colorscheme ayu | endif
call setqflist([])
let SessionLoad = 1
let s:so_save = &so | let s:siso_save = &siso | set so=0 siso=0
let v:this_session=expand("<sfile>:p")
silent only
cd ~/Source/FEECa
if expand('%') == '' && !&modified && line('$') <= 1 && getline(1) == ''
  let s:wipebuf = bufnr('%')
endif
set shortmess=aoO
badd +6 ~/Source/ngsolve-tutorials/docs/html/jupyter-files/unit-1.1-poisson/poisson.ipynb
badd +1 ~/.dotfiles/tag-nvim/config/nvim/init.syntax-range
argglobal
%argdel
edit ~/.dotfiles/tag-nvim/config/nvim/init.syntax-range
set splitbelow splitright
wincmd _ | wincmd |
vsplit
1wincmd h
wincmd w
set nosplitbelow
set nosplitright
wincmd t
set winminheight=0
set winheight=1
set winminwidth=0
set winwidth=1
exe 'vert 1resize ' . ((&columns * 52 + 52) / 105)
exe 'vert 2resize ' . ((&columns * 52 + 52) / 105)
argglobal
setlocal fdm=manual
setlocal fde=0
setlocal fmr={{{,}}}
setlocal fdi=#
setlocal fdl=0
setlocal fml=1
setlocal fdn=20
setlocal fen
silent! normal! zE
let s:l = 22 - ((17 * winheight(0) + 25) / 51)
if s:l < 1 | let s:l = 1 | endif
exe s:l
normal! zt
22
normal! 01|
lcd ~/Source/ngsolve-tutorials/docs/html/jupyter-files/unit-1.1-poisson
wincmd w
argglobal
if bufexists("~/Source/ngsolve-tutorials/docs/html/jupyter-files/unit-1.1-poisson/poisson.ipynb") | buffer ~/Source/ngsolve-tutorials/docs/html/jupyter-files/unit-1.1-poisson/poisson.ipynb | else | edit ~/Source/ngsolve-tutorials/docs/html/jupyter-files/unit-1.1-poisson/poisson.ipynb | endif
setlocal fdm=expr
setlocal fde=Foldexpr_markdown(v:lnum)
setlocal fmr={{{,}}}
setlocal fdi=#
setlocal fdl=99
setlocal fml=1
setlocal fdn=20
setlocal fen
let s:l = 44 - ((6 * winheight(0) + 25) / 51)
if s:l < 1 | let s:l = 1 | endif
exe s:l
normal! zt
44
normal! 0
lcd ~/Source/ngsolve-tutorials/docs/html/jupyter-files/unit-1.1-poisson
wincmd w
2wincmd w
exe 'vert 1resize ' . ((&columns * 52 + 52) / 105)
exe 'vert 2resize ' . ((&columns * 52 + 52) / 105)
tabnext 1
if exists('s:wipebuf') && getbufvar(s:wipebuf, '&buftype') isnot# 'terminal'
"   silent exe 'bwipe ' . s:wipebuf
endif
" unlet! s:wipebuf
set winheight=1 winwidth=20 winminheight=1 winminwidth=1 shortmess=filnxtToOFcI
let s:sx = expand("<sfile>:p:r")."x.vim"
if file_readable(s:sx)
  exe "source " . fnameescape(s:sx)
endif
let &so = s:so_save | let &siso = s:siso_save

" Support for special windows like quick-fix and plug-in windows.
" Everything down here is generated by vim-session (not supported
" by :mksession out of the box).

2wincmd w
tabnext 1
if exists('s:wipebuf')
  if empty(bufname(s:wipebuf))
if !getbufvar(s:wipebuf, '&modified')
  let s:wipebuflines = getbufline(s:wipebuf, 1, '$')
  if len(s:wipebuflines) <= 1 && empty(get(s:wipebuflines, 0, ''))
    silent execute 'bwipeout' s:wipebuf
  endif
endif
  endif
endif
doautoall SessionLoadPost
unlet SessionLoad
" vim: ft=vim ro nowrap smc=128
