nmap <silent> qpe <Plug>(PickerEdit)
nmap <silent> qps <Plug>(PickerSplit)
nmap <silent> qpt <Plug>(PickerTabedit)
nmap <silent> qpv <Plug>(PickerVsplit)
nmap <silent> qpb <Plug>(PickerBuffer)
nmap <silent> qpBs <Plug>(PickerBufferSplit)
nmap <silent> qpBv <Plug>(PickerBufferVsplit)
nmap <silent> qpT <Plug>(PickerTag)
" nmap <silent> qp <Plug>(PickerStag)
nmap <silent> qpBT <Plug>(PickerBufferTag)
nmap <silent> qpH <Plug>(PickerHelp)
