
# Temp dir
export TMPDIR="/tmp"

# Source global definitions
#if [ -f /etc/bashrc ]; then
	#. /etc/bashrc
#fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

#/rw/config/rc.local
# DO NOT DO THIS!!!
#exec '/rw/config/rc.local'
